TIPO_DE_REGISTRO: IDENTIFICAÇÃO DO REGISTRO TRANSAÇÃO | 001 | 001 | 9(001) | 2
COD_MULTA: CODIGO DA MULTA | 002 | 002 | X(001) | NOTA 35
DATA_DA_MULTA: DATA DA MULTA | 003 | 010 | 9(008) | NOTA 35
MULTA: VALOR/PERCENTUAL A SER APLICADO | 011 | 023 | 9(013) | NOTA 35
BRANCOS: COMPLEMENTO DE REGISTRO | 024 | 394 | X(370)
NUMERO_SEQUENCIAL: NUMERO SEQUENCIAL DO REGISTRO NO ARQUIVO | 395 | 400 | 9(006)