TIPO_DE_REGISTRO: IDENTIFICAÇÃO DO REGISTRO TRANSAÇÃO|001|001|9(01)|1
CODIGO_DE_INSCRICAO: IDENTIFICAÇÃO DO TIPO DE INSCRIÇÃO/EMPRESA|002|003|9(02)|01=CPF 02=CNPJ
NUMERO_DE_INSCRICAO: NÚMERO DE INSCRIÇÃO DA EMPRESA (CPF/CNPJ)|004|017|9(14)|
AGENCIA: AGÊNCIA MANTENEDORA DA CONTA|018|021|9(04)|
ZEROS: COMPLEMENTO DE REGISTRO|022|023|9(02)|“00”
CONTA: NÚMERO DA CONTA CORRENTE DA EMPRESA|024|028|9(05)|
DAC: DÍGITO DE AUTO CONFERÊNCIA AG/CONTA EMPRESA|029|029|9(01)|
BRANCOS: COMPLEMENTO DE REGISTRO|030|037|X(08)|
USO_DA_EMPRESA: IDENTIFICAÇÃO DO TÍTULO NA EMPRESA|038|062|X(25)|NOTA 2
NOSSO_NUMERO: IDENTIFICAÇÃO DO TÍTULO NO BANCO|063|070|9(08)|
BRANCOS_1: COMPLEMENTO DO REGISTRO|071|082|X(12)|
CARTEIRA: NUMERO DA CARTEIRA|083|085|9(03)|NOTA 5
NOSSO_NUMERO: IDENTIFICAÇÃO DO TÍTULO NO BANCO|086|093|9(08)|NOTA 3
DAC_NOSSO_NUMERO: DAC DO NOSSO NÚMERO|094|094|9(01)|NOTA 3
BRANCOS_2: COMPLEMENTO DO REGISTRO|095|107|X(13)|
COD_CARTEIRA: CÓDIGO DA CARTEIRA|108|108|X(01)|NOTA 5
COD_DE_OCORRENCIA: IDENTIFICAÇÃO DA OCORRÊNCIA|109|110|9(02)|NOTA 17
DATA_DE_OCORRENCIA: DATA DE OCORRÊNCIA NO BANCO|111|116|9(06)|DDMMAA
N_DO_DOCUMENTO: Nº DO DOCUMENTO DE COBRANÇA (DUPL, NP ETC)|117|126|X(10)|NOTA 18
NOSSO_NUMERO: CONFIRMAÇÃO DO NÚMERO DO TÍTULO NO BANCO|127|134|9(08)|
BRANCOS_3: COMPLEMENTO DO REGISTRO|135|146|X(12)|
VENCIMENTO: DATA DE VENCIMENTO DO TÍTULO|147|152|9(06)|DDMMAA
VALOR_DO_TITULO: VALOR NOMINAL DO TÍTULO|153|165|9(11)V9(2)|
CODIGO_DO_BANCO: NÚMERO DO BANCO NA CÂMARA DE COMPENSAÇÃO|166|168|9(03)|
AGENCIA_COBRADORA: AG. COBRADORA, AG. DE LIQUIDAÇÃO OU BAIXA|169|172|9(04)|NOTA 9
DAC_AG_COBRADORA: DAC DA AGÊNCIA COBRADORA|173|173|9(01)|
ESPECIE: ESPÉCIE DO TÍTULO|174|175|9(02)|NOTA 10
TARIFA_DE_COBRANÇA: VALOR DA DESPESA DE COBRANÇA|176|188|9(11)V9(2)|
BRANCOS_4: COMPLEMENTO DO REGISTRO|189|214|X(26)|
VALOR_DO_IOF: VALOR DO IOF A SER |RECOLHIDO (NOTAS SEGURO)|215|227|9(11)V9(2)|
VALOR_ABATIMENTO: VALOR DO ABATIMENTO CONCEDIDO|228|240|9(11)V((2)|NOTA 19
DESCONTOS: VALOR DO DESCONTO CONCEDIDO|241|253|9(11)V9(2)|NOTA 19
VALOR_PRINCIPAL: VALOR LANÇADO EM CONTA CORRENTE|254|266|9(11)V9(2)|
JUROS_DE_MORA_MULTA: VALOR DE MORA E MULTA|267|279|9(11)V9(2)|
OUTROS_CREDITOS: VALOR DE OUTROS CRÉDITOS|280|292|9(11)V9(2)|
BOLETO_DDA: INDICADOR DE BOLETO DDA|293|293|X(01)|NOTA 34
BRANCOS_5: COMPLEMENTO DO REGISTRO|294|295|X(02)|
DATA_CREDITO: DATA DE CRÉDITO DESTA LIQUIDAÇÃO|296|301|X(06)|DDMMAA
INSTRCANCELADA: CÓDIGO DA INSTRUÇÃO CANCELADA|302|305|9(04)|NOTA 20
BRANCOS_6: COMPLEMENTO DE REGISTRO|306|311|X(06)|
ZEROS: COMPLEMENTO DE REGISTRO|312|324|9(13)|
NOME_DO_PAGADOR: NOME DO PAGADOR|325|354|X(30)|
BRANCOS_7: COMPLEMENTO DO REGISTRO|355|377|X(23)|
ERROS_MENSAGEM_INFORMATIVA: REGISTROS REJEITADOS OU ALEGAÇÃO DO PAGADOR OU|378|385|X(08)|NOTA 20
BRANCOS_8: REGISTRO DE MENSAGEM INFORMATIVA|386|392|X(07)|
COD_DE_LIQUIDACAO: COMPLEMENTO DO REGISTRO|393|394|X(02)|NOTA 28
NUMERO_SEQUENCIAL: MEIO PELO QUAL O TÍTULO FOI LIQUIDADO|395|400|9(06)|
