TIPO_DE_REGISTRO: IDENTIFICAÇÃO DO REGISTRO TRANSAÇÃO | 001 | 001 | 9(01) | 1
CODIGO_DE_INSCRIÇÃO: IDENTIFICAÇÃO DO TIPO DE INSCRIÇÃO/EMPRESA | 002 | 003 | 9(02) | 01=CPF 02=CNPJ
NUMERO_DE_INSCRIÇÃO: NÚMERO DE INSCRIÇÃO DA EMPRESA (CPF/CNPJ) | 004 | 017 | 9(14) |
AGENCIA: AGÊNCIA MANTENEDORA DA CONTA | 018 | 021 | 9(04) |
ZEROS: COMPLEMENTO DE REGISTRO | 022 | 023 | 9(02) | “00”
CONTA: NÚMERO DA CONTA CORRENTE DA EMPRESA | 024 | 028 | 9(05) |
DAC: DÍGITO DE AUTO CONFERÊNCIA AG/CONTA EMPRESA | 029 | 029 | 9(01) |
BRANCOS: COMPLEMENTO DE REGISTRO | 030 | 037 | X(08) |
USO_DA_EMPRESA: IDENTIFICAÇÃO DO TÍTULO NA EMPRESA | 038 | 062 | X(25) | NOTA 2
NOSSO_NUMERO: IDENTIFICAÇÃO DO TÍTULO NO BANCO | 063 | 070 | 9(08) |
AGÊNCIA_CONTA_DO_CHEQUE: AGÊNCIA CONTA E DAC DE DÉBITO DO CHEQUE | 071 | 082 | X(12) | NOTA 33
CARTEIRA: NUMERO DA CARTEIRA | 083 | 085 | 9(03) | NOTA 5
NOSSO_NÚMERO: IDENTIFICAÇÃO DO TÍTULO NO BANCO | 086 | 093 | 9(08) | NOTA 3
DAC_NOSSO_NÚMERO: DAC DO NOSSO NÚMERO | 094 | 094 | 9(01) | NOTA 3
BRANCOS: COMPLEMENTO DO REGISTRO | 095 | 107 | X(13) |
CARTEIRA: CÓDIGO DA CARTEIRA | 108 | 108 | X(01) | NOTA 5
COD_DE_OCORRÊNCIA: IDENTIFICAÇÃO DA OCORRÊNCIA | 109 | 110 | 9(02) | NOTA 17
DATA_DE_OCORRÊNCIA: DATA DE OCORRÊNCIA NO BANCO | 111 | 116 | 9(06) | DDMMAA
N_DO_DOCUMENTO: Nº DO DOCUMENTO DE COBRANÇA (DUPL, NP ETC) | 117 | 126 | X(10) | NOTA 18
NOSSO_NÚMERO: CONFIRMAÇÃO DO NÚMERO DO TÍTULO NO BANCO | 127 | 134 | 9(08) |
BRANCOS: COMPLEMENTO DO REGISTRO | 135 | 146 | X(12) |
ZEROS: COMPLEMENTO DO REGISTRO | 147 | 152 | 9(06) |
VALOR_DO_TITULO: VALOR NOMINAL DO TÍTULO | 153 | 165 | 9(11) | V9(2)
CODIGO_DO_BANCO: NÚMERO DO BANCO NA CÂMARA DE COMPENSAÇÃO | 166 | 168 | 9(03) |
AGENCIA_COBRADORA: AG. COBRADORA, AG. DE LIQUIDAÇÃO OU BAIXA | 169 | 172 | 9(04) | NOTA 9
DAC_AG_COBRADORA: DAC DA AGÊNCIA COBRADORA | 173 | 173 | 9(01) |
BRANCOS: COMPLEMENTO DO REGISTRO | 174 | 175 | X(02) |
ZEROS: COMPLEMENTO DO REGISTRO | 176 | 253 | 9(78) |
VALOR_DO_CHEQUE: VALOR DO CHEQUE | 254 | 266 | 9(11) | V9(2)
ZEROS: COMPLEMENTO DO REGISTRO | 267 | 292 | 9(26) |
BRANCOS: COMPLEMENTO DO REGISTRO | 293 | 301 | X(09) |
ZEROS: COMPLEMENTO DO REGISTRO | 302 | 324 | 9(23) |
BANDA_MAGNETICA: BANDA MAGNÉTICA DO CHEQUE (CMC-7) | 325 | 354 | X(30) |
BRANCOS: COMPLEMENTO DO REGISTRO | 355 | 377 | X(23) |
MOTIVO: MOTIVO DE DEVOLUÇÃO DO CHEQUE | 378 | 379 | X(02) | NOTA 20
BRANCOS: COMPLEMENTO DO REGISTRO | 380 | 394 | X(15) |
NUMERO_SEQUENCIAL: NÚMERO SEQÜENCIAL DO REGISTRO NO ARQUIVO | 395 | 400 | 9(06) |