TIPO_DE_REGISTRO: IDENTIFICAÇÃO DO REGISTRO TRAILER | 001 | 001 | 9(01) | 9
CODIGO_DE_RETORNO: IDENTIFICAÇÃO DE ARQUIVO RETORNO | 002 | 002 | 9(01) | 2
CODIGO_DE_SERVICO: IDENTIFICAÇÃO DO TIPO DE SERVIÇO | 003 | 004 | 9(02) | 01
CODIGO_DO_BANCO: IDENTIFICAÇÃO DO BANCO NA COMPENSAÇÃO | 005 | 007 | 9(03) | 341
BRANCOS: COMPLEMENTO DE REGISTRO | 008 | 017 | X(10) | 
QTDE_DE_TITULOS: QTDE. DE TÍTULOS EM COBR. SIMPLES | 018 | 025 | 9(08) | NOTA 21
VALOR_TOTAL: VR TOTAL DOS TÍTULOS EM COBRANÇA SIMPLES | 026 | 039 | 9(12)V9(2) | NOTA 21
AVISO_BANCÁRIO: REFERÊNCIA DO AVISO BANCÁRIO | 040 | 047 | X(08) | NOTA 22
BRANCOS: COMPLEMENTO DO REGISTRO | 048 | 057 | X(10) | 
QTDE_DE_TITULOS: QTDE DE TÍTULOS EM COBRANÇA/VINCULADA | 058 | 065 | 9(08) | NOTA 21
VALOR: TOTAL | VR TOTAL DOS TÍTULOS EM COBRANÇA/VINCULADA | 066 | 079 | 9(12)V9(2) | NOTA 21
AVISO_BANCÁRIO: REFERÊNCIA DO AVISO BANCÁRIO | 080 | 087 | X(08) | NOTA 22
BRANCOS: COMPLEMENTO DO REGISTRO | 088 | 177 | X(90) | 
QTDE_DE_TITULOS: QTDE. DE TÍTULOS EM COBR. DIRETA./ESCRITURAL | 178 | 185 | 9(08) | NOTA 21
VALOR_TOTAL: VR TOTAL DOS TÍTULOS EM COBR. DIRETA/ESCRIT. | 186 | 199 | 9(12)V9(2) | NOTA 21
AVISO_BANCARIO: REFERÊNCIA DO AVISO BANCÁRIO | 200 | 207 | X(08) | NOTA 22
CONTROLE_DO_ARQUIVO: NÚMERO SEQÜENCIAL DO ARQUIVO RETORNO | 208 | 212 | 9(05) |
QTDE_DE_DETALHES: QUANTIDADE DE REGISTROS DE TRANSAÇÃO | 213 | 220 | 9(08) |
VLR_TOTAL_INFORMADO: VALOR DOS TÍTULOS INFORMADOS NO ARQUIVO | 221 | 234 | 9(12)V9(2) |
BRANCOS: COMPLEMENTO DO REGISTRO | 235 | 394 | X(160) | 
NUMERO_SEQUENCIAL: NÚMERO SEQÜENCIAL DO REGISTRO NO ARQUIVO | 395 | 400 | 9(06) |