TIPO_DE_REGISTRO: IDENTIFICACAO DO REGISTRO TRANSACAO | 001 | 001 | 9(01) | 1
CODIGO_DE_INSCRICAO: TIPO DE INSCRICAO DA EMPRESA | 002 | 003 | 9(02) | NOTA 1
NUMERO_DE_INSCRICAO: Nº DE INSCRICAO DA EMPRESA (CPF/CNPJ) | 004 | 017 | 9(14) | NOTA 1
AGENCIA: AGENCIA MANTENEDORA DA CONTA | 018 | 021 | 9(04)
ZEROS: COMPLEMENTO DE REGISTRO | 022 | 023 | 9(02) | “00”
CONTA: NUMERO DA CONTA CORRENTE DA EMPRESA | 024 | 028 | 9(05)
DAC: DÍGITO DE AUTO CONFERENCIA AG/CONTA EMPRESA | 029 | 029 | 9(01)
BRANCOS: COMPLEMENTO DE REGISTRO | 030 | 033 | X(04)
INSTRUCAO_ALEGACAO: COD.INSTRUCAO/ALEGACAO A SER CANCELADA | 034 | 037 | 9(04) | NOTA 27
USO_DA_EMPRESA: IDENTIFICACAO DO TÍTULO NA EMPRESA | 038 | 062 | X(25) | NOTA 2
NOSSO_NUMERO: IDENTIFICACAO DO TÍTULO NO BANCO | 063 | 070 | 9(08) | NOTA 3
QTDE_DE_MOEDA: QUANTIDADE DE MOEDA VARIÁVEL | 071 | 083 | 9(08)V9(5) | NOTA 4
N_DA_CARTEIRA: NUMERO DA CARTEIRA NO BANCO | 084 | 086 | 9(03) | NOTA 5
USO_DO_BANCO: IDENTIFICACAO DA OPERACAO NO BANCO | 087 | 107 | X(21)
CARTEIRA: CODIGO DA CARTEIRA | 108 | 108 | X(01) | NOTA 5
COD_DE_OCORRENCIA: IDENTIFICACAO DA OCORRENCIA | 109 | 110 | 9(02) | NOTA 6
N_DO_DOCUMENTO: Nº DO DOCUMENTO DE COBRANÇA (DUPL.,NP ETC.) | 111 | 120 | X(10) | NOTA 18
VENCIMENTO: DATA DE VENCIMENTO DO TÍTULO | 121 | 126 | 9(06) | NOTA 7
VALOR_DO_TÍTULO: VALOR NOMINAL DO TÍTULO | 127 | 139 | 9(11) |V9(2) | NOTA 8
CODIGO_DO_BANCO: Nº DO BANCO NA CÂMARA DE COMPENSACAO | 140 | 142 | 9(03) | 341
AGENCIA: COBRADORA AGENCIA ONDE O TÍTULO SERÁ COBRADO | 143 | 147 | 9(05) | NOTA 9
ESPECIE: ESPECIE DO TÍTULO | 148 | 149 | X(02) | NOTA 10
ACEITE: IDENTIFICACAO DE TÍTULO ACEITO OU NÃO ACEITO | 150 | 150 | X(01) | A=ACEITE N=NÃO ACEITE
DATA_DE_EMISSÃO: DATA DA EMISSÃO DO TÍTULO | 151 | 156 | 9(06) | NOTA 31
INSTRUCAO_1: 1ª INSTRUCAO DE COBRANÇA | 157 | 158 | X(02) | NOTA 11
INSTRUCAO_2: 2ª INSTRUCAO DE COBRANÇA | 159 | 160 | X(02) | NOTA 11
JUROS_DE_1_DIA: VALOR DE MORA POR DIA DE ATRASO | 161 | 173 | 9(11) |V9(2) | NOTA 12
DESCONTO_ATE: DATA LIMITE PARA CONCESSÃO DE DESCONTO | 174 | 179 | 9(06) | DDMMAA
VALOR_DO_DESCONTO: VALOR DO DESCONTO A SER CONCEDIDO | 180 | 192 | 9(11)V9(2) | NOTA 13
VALOR_DO_IOF: VALOR DO I.O.F. RECOLHIDO P/ NOTAS SEGURO | 193 | 205 | 9(11)V((2) | NOTA 14
ABATIMENTO: VALOR DO ABATIMENTO A SER CONCEDIDO | 206 | 218 | 9(11)V9(2) | NOTA 13
CODIGO_DE_INSCRICAO: IDENTIFICACAO DO TIPO DE INSCRICAO/PAGADOR | 219 | 220 | 9(02) | 01=CPF 02=CNPJ
NUMERO_DE_INSCRICAO: Nº DE INSCRICAO DO PAGADOR (CPF/CNPJ) | 221 | 234 | 9(14)
NOME: NOME DO PAGADOR | 235 | 264 | X(30) | NOTA 15
BRANCOS: COMPLEMENTO DE REGISTRO | 265 | 274 | X(10) | NOTA 15
LOGRADOURO: RUA, NUMERO E COMPLEMENTO DO PAGADOR | 275 | 314 | X(40)
BAIRRO: BAIRRO DO PAGADOR | 315 | 326 | X(12)
CEP: CEP DO PAGADOR | 327 | 334 | 9(08)
CIDADE: CIDADE DO PAGADOR | 335 | 349 | X(15)
ESTADO: UF DO PAGADOR | 350 | 351 | X(02)
SACADOR_AVALISTA: NOME DO SACADOR OU AVALISTA | 352 | 381 | X(30) | NOTA 16
BRANCOS: COMPLEMENTO DO REGISTRO | 382 | 385 | X(04)
DATA_DE_MORA: DATA DE MORA | 386 | 391 | 9(06) | DDMMAA
PRAZO: QUANTIDADE DE DIAS | 392 | 393 | 9(02) | NOTA 11 (A)
BRANCOS: COMPLEMENTO DO REGISTRO | 394 | 394 | X(01)
NUMERO_SEQUENCIAL: Nº SEQUENCIAL DO REGISTRO NO ARQUIVO | 395 | 400 | 9(06)
