TIPO_DE_REGISTRO: IDENTIFICAÇÃO DO REGISTRO HEADER | 001 | 001 | 9(01) | 0
OPERACAO: TIPO DE OPERAÇÃO - REMESSA | 002 | 002 | 9(01)|  1
LITERAL_DE_REMESSA: IDENTIFICAÇÃO POR EXTENSO DO MOVIMENTO|  003 | 009 | X(07) | REMESSA
CODIGO_DO_SERVICO: IDENTIFICAÇÃO DO TIPO DE SERVIÇO|  010|  011|  9(02)| 01
LITERAL_DE_SERVICO: IDENTIFICAÇÃO POR EXTENSO DO TIPO DE SERVIÇO | 012 | 026 | X(15) | COBRANCA
AGENCIA: AGÊNCIA MANTENEDORA DA CONTA | 027 | 030 | 9(04)
ZEROS: COMPLEMENTO DE REGISTRO | 031 | 032 | 9(02) | 00
CONTA: NÚMERO DA CONTA CORRENTE DA EMPRESA | 033 | 037 | 9 | (05)
DAC: DÍGITO DE AUTO CONFERÊNCIA AG/CONTA EMPRESA | 038 | 038 | 9(01)
BRANCOS: COMPLEMENTO DO REGISTRO | 039 | 046 | X(08)
NOME_DA_EMPRESA: NOME POR EXTENSO DA "EMPRESA MÃE" | 047 | 076 | X(30)
CODIGO_DO_BANCO: Nº DO BANCO NA CÂMARA DE COMPENSAÇÃO | 077 | 079 | 9(03) | 341
NOME_DO_BANCO: NOME POR EXTENSO DO BANCO COBRADOR | 080 | 094 | X(15) | BANCO ITAU SA
DATA_DE_GERACAO: DATA DE GERAÇÃO DO ARQUIVO | 095 | 100 | 9(06) | DDMMAA
BRANCOS_2: COMPLEMENTO DO REGISTRO | 101 | 394 | X(294)
NUMERO_SEQUENCIAL: NÚMERO SEQÜENCIAL DO REGISTRO NO ARQUIVO | 395 | 400 | 9(06) | 000001