TIPO_DE_REGISTRO: IDENTIFICAÇÃO DO REGISTRO TRAILER | 001 | 001 | 9(01) | 9
BRANCOS: COMPLEMENTO DO REGISTRO | 002 | 394 | X(393)
NUMERO_SEQUENCIAL: NÚMERO SEQÜENCIAL DO REGISTRO NO ARQUIVO | 395 | 400 | 9(06)