ocorrencias_de_remessa:
  01: Remessa
  02: Pedido de Baixa
  04: Consessão de Abatimento
  05: Cancelamento do Abatimento
  06: Alteracao de Vencimento
  07: Alteracao de Uso da Empresa
  08: Alteracao do seu numero
  09: Protestar
  10: Não Protestar
  11: Protestar para fins falimentares
  18: Sustar Protesto

ocorrencias_de_retorno:
  02: ENTRADA CONFIRMADA COM POSSIBILIDADE DE MENSAGEM (NOTA 20 – TABELA 10)
  03: ENTRADA REJEITADA (NOTA 20 – TABELA 1)
  04: ALTERAÇÃO DE DADOS – NOVA ENTRADA OU ALTERAÇÃO/EXCLUSÃO DE DADOS ACATADA
  05: ALTERAÇÃO DE DADOS – BAIXA
  06: LIQUIDAÇÃO NORMAL
  07: LIQUIDAÇÃO PARCIAL – COBRANÇA INTELIGENTE (B2B)
  08: LIQUIDAÇÃO EM CARTÓRIO
  09: BAIXA SIMPLES
  10: BAIXA POR TER SIDO LIQUIDADO
  11: EM SER (SÓ NO RETORNO MENSAL)
  12: ABATIMENTO CONCEDIDO
  13: ABATIMENTO CANCELADO
  14: VENCIMENTO ALTERADO
  15: BAIXAS REJEITADAS (NOTA 20 – TABELA 4)
  16: INSTRUÇÕES REJEITADAS (NOTA 20 – TABELA 3)
  17: ALTERAÇÃO/EXCLUSÃO DE DADOS REJEITADOS (NOTA 20 – TABELA 2)
  18: COBRANÇA CONTRATUAL – INSTRUÇÕES/ALTERAÇÕES REJEITADAS/PENDENTES (NOTA 20 – TABELA 5)
  19: CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE PROTESTO
  20: CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE SUSTAÇÃO DE PROTESTO /TARIFA
  21: CONFIRMA RECEBIMENTO DE INSTRUÇÃO DE NÃO PROTESTAR
  23: TÍTULO ENVIADO A CARTÓRIO/TARIFA
  24: INSTRUÇÃO DE PROTESTO REJEITADA / SUSTADA / PENDENTE (NOTA 20 – TABELA 7)
  25: ALEGAÇÕES DO PAGADOR (NOTA 20 – TABELA 6)
  26: TARIFA DE AVISO DE COBRANÇA
  27: TARIFA DE EXTRATO POSIÇÃO (B40X)
  28: TARIFA DE RELAÇÃO DAS LIQUIDAÇÕES
  29: TARIFA DE MANUTENÇÃO DE TÍTULOS VENCIDOS
  30: DÉBITO MENSAL DE TARIFAS (PARA ENTRADAS E BAIXAS)
  32: BAIXA POR TER SIDO PROTESTADO
  33: CUSTAS DE PROTESTO
  34: CUSTAS DE SUSTAÇÃO
  35: CUSTAS DE CARTÓRIO DISTRIBUIDOR
  36: CUSTAS DE EDITAL
  37: TARIFA DE EMISSÃO DE BOLETO/TARIFA DE ENVIO DE DUPLICATA
  38: TARIFA DE INSTRUÇÃO
  39: TARIFA DE OCORRÊNCIAS
  40: TARIFA MENSAL DE EMISSÃO DE BOLETO/TARIFA MENSAL DE ENVIO DE DUPLICATA
  41: DÉBITO MENSAL DE TARIFAS – EXTRATO DE POSIÇÃO (B4EP/B4OX)
  42: DÉBITO MENSAL DE TARIFAS – OUTRAS INSTRUÇÕES
  43: DÉBITO MENSAL DE TARIFAS – MANUTENÇÃO DE TÍTULOS VENCIDOS
  44: DÉBITO MENSAL DE TARIFAS – OUTRAS OCORRÊNCIAS
  45: DÉBITO MENSAL DE TARIFAS – PROTESTO
  46: DÉBITO MENSAL DE TARIFAS – SUSTAÇÃO DE PROTESTO
  47: BAIXA COM TRANSFERÊNCIA PARA DESCONTO
  48: CUSTAS DE SUSTAÇÃO JUDICIAL
  51: TARIFA MENSAL REF A ENTRADAS BANCOS CORRESPONDENTES NA CARTEIRA
  52: TARIFA MENSAL BAIXAS NA CARTEIRA
  53: TARIFA MENSAL BAIXAS EM BANCOS CORRESPONDENTES NA CARTEIRA
  54: TARIFA MENSAL DE LIQUIDAÇÕES NA CARTEIRA
  55: TARIFA MENSAL DE LIQUIDAÇÕES EM BANCOS CORRESPONDENTES NA CARTEIRA
  56: CUSTAS DE IRREGULARIDADE
  57: INSTRUÇÃO CANCELADA (NOTA 20 – TABELA 8)
  59: BAIXA POR CRÉDITO EM C/C ATRAVÉS DO SISPAG
  60: ENTRADA REJEITADA CARNÊ (NOTA 20 – TABELA 1)
  61: TARIFA EMISSÃO AVISO DE MOVIMENTAÇÃO DE TÍTULOS (2154)
  62: DÉBITO MENSAL DE TARIFA – AVISO DE MOVIMENTAÇÃO DE TÍTULOS (2154)
  63: TÍTULO SUSTADO JUDICIALMENTE


instrucoes_de_cobranca:
  09: Protestar
  10: Não Protestar
  05: Receber conforme instruções no próprio titulo
  02: Devolver após 05 dias do vencimento
  06: Devolver após 10 dias do vencimento
  07: Devolver após 15 dias do vencimento
  08: Devolver após 20 dias do vencimento
  11: Devolver após 25 dias do vencimento
  03: Devolver após 30 dias do vencimento
  12: Devolver após 35 dias do vencimento
  13: Devolver após 40 dias do vencimento
  14: Devolver após 45 dias do vencimento
  15: Devolver após 50 dias do vencimento
  16: Devolver após 55 dias do vencimento
  17: Devolver após 60 dias do vencimento
  18: Devolver após 90 dias do vencimento
  19: Não receber após 05 dias do vencimento
  20: Não receber após 10 dias do vencimento
  21: Não receber após 15 dias do vencimento
  22: Não receber após 20 dias do vencimento
  23: Não receber após 25 dias do vencimento
  24: Não receber após 30 dias do vencimento
  25: Não receber após 35 dias do vencimento
  26: Não receber após 40 dias do vencimento
  27: Não receber após 45 dias do vencimento
  28: Não receber após 50 dias do vencimento
  29: Não receber após 55 dias do vencimento
  30: Importancia de Desconto por dia
  31: Não receber após 60 dias do vencimento
  32: Não receber após 90 dias do vencimento
  33: CONCEDER ABATIMENTO REF. À PIS-PASEP/COFIN/CSSL, MESMO APÓS VENCIMENTO
  34: PROTESTAR APÓS XX DIAS CORRIDOS DO VENCIMENTO
  35: PROTESTAR APÓS XX DIAS ÚTEIS DO VENCIMENTO
  37: RECEBER ATÉ O ÚLTIMO DIA DO MÊS DE VENCIMENTO
  38: CONCEDER DESCONTO MESMO APÓS VENCIMENTO
  39: NÃO RECEBER APÓS O VENCIMENTO
  40: CONCEDER DESCONTO CONFORME NOTA DE CRÉDITO